sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - echo ' ----------------- STEP 1) BUILD DOCKER IMAGE ----------------- '
  - docker build -t mlflow .
before_deploy:
  - echo ' ----------------- STEP 2) DOCKER PUSH ----------------- '
